#keycloak:
#    auth-server-url: http://localhost:8080/auth
#    bearer-only: true
#    credentials:
#        secret: 62564a15-92fc-42cf-ba2f-910d62c6e7c5
#    public-client: true
#    realm: test-keycloak
#    resource: demo-app-be
#    ssl-required: external
#    use-resource-role-mappings: true
server:
    port: 8084
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
storage:
    location: ./uploads